Cooking/Cooking/Models/Category.cs
using System;
using System.Collections.Generic;

namespace Cooking.Models
{
    public partial class Category
    {
        public Category()
        {
            Measure = new HashSet<Measure>();
        }

        public string CategoryCode { get; set; }
        public string Name { get; set; }
        public string MeasureCode { get; set; }

        public virtual Measure MeasureCodeNavigation { get; set; }
        public virtual ICollection<Measure> Measure { get; set; }
    }
}

Cooking/Cooking/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cooking.Models;

namespace Cooking.Controllers
{
    public class CategoryController : Controller
    {
        private readonly CookingContext _context;

        public CategoryController(CookingContext context)
        {
            _context = context;
        }

        // GET: Category
        public async Task<IActionResult> Index()
        {
            var cookingContext = _context.Category.Include(c => c.MeasureCodeNavigation).OrderBy(m=>m.Name);
            return View(await cookingContext.ToListAsync());
        }

        // GET: Category/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .Include(c => c.MeasureCodeNavigation)
                .FirstOrDefaultAsync(m => m.CategoryCode == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Category/Create
        public IActionResult Create()
        {
            ViewData["MeasureCode"] = new SelectList(_context.Measure, "MeasureCode", "MeasureCode");
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryCode,Name,MeasureCode")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MeasureCode"] = new SelectList(_context.Measure, "MeasureCode", "MeasureCode", category.MeasureCode);
            return View(category);
        }

        // GET: Category/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            ViewData["MeasureCode"] = new SelectList(_context.Measure, "MeasureCode", "MeasureCode", category.MeasureCode);
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CategoryCode,Name,MeasureCode")] Category category)
        {
            if (id != category.CategoryCode)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryCode))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MeasureCode"] = new SelectList(_context.Measure, "MeasureCode", "MeasureCode", category.MeasureCode);
            return View(category);
        }

        // GET: Category/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .Include(c => c.MeasureCodeNavigation)
                .FirstOrDefaultAsync(m => m.CategoryCode == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var category = await _context.Category.FindAsync(id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(string id)
        {
            return _context.Category.Any(e => e.CategoryCode == id);
        }
    }
}

Cooking/Cooking/Controllers/MeasureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cooking.Models;

namespace Cooking.Controllers
{
    public class MeasureController : Controller
    {
        private readonly CookingContext _context;

        public MeasureController(CookingContext context)
        {
            _context = context;
        }

        // GET: Measure
        public async Task<IActionResult> Index(string CategoryCode)
        {
            if(!string.IsNullOrEmpty(CategoryCode))
            {
                Response.Cookies.Append("CategoryCode", CategoryCode);
            }
            else if(Request.Query["CategoryCode"].Any())
            {
                Response.Cookies.Append("CategoryCode", Request.Query["CategoryCode"].ToString());
            }
            else if(Request.Cookies["CategoryCode"]!=null)
            {
                CategoryCode= Request.Cookies["CategoryCode"].ToString();
            }
            else
            {
                TempData["message"] = "Please select a Category Code to display its measures";
                return RedirectToAction("Index", "Category");
            }

            var CategoryRecord = _context.Category.Where(b => b.CategoryCode == CategoryCode)
                                    .FirstOrDefault();
            var BaseMeasure = _context.Measure.Where(x => x.CategoryCode == CategoryRecord.CategoryCode && x.RatioToBase == 1)
                                .FirstOrDefault();

            //var CategoryRecord = from c in _context.Category
            //                     join cm in _context.Measure on
            //                    c.MeasureCode == cm.MeasureCode
            //                     select c;

            if (!string.IsNullOrEmpty(BaseMeasure.Name))
            {
                ViewData["CategoryName"] = CategoryRecord.Name;
                ViewData["MeasureName"] = BaseMeasure.Name;
            }
            else
            {
                ViewData["CategoryName"] = CategoryRecord.Name;
                ViewData["MeasureName"] = "N/A";
            }
            

            var cookingContext = _context.Measure.Include(m => m.CategoryCodeNavigation)
                .Where(m=>m.CategoryCode==CategoryCode)
                .OrderBy(x=>x.Name);
            return View(await cookingContext.ToListAsync());
        }

        // GET: Measure/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var measure = await _context.Measure
                .Include(m => m.CategoryCodeNavigation)
                .FirstOrDefaultAsync(m => m.MeasureCode == id);
            if (measure == null)
            {
                return NotFound();
            }

            return View(measure);
        }

        // GET: Measure/Create
        public IActionResult Create()
        {
            string Catcode = string.Empty;

            if(Request.Cookies["CategoryCode"]!=null)
            {
                Catcode = Request.Cookies["CategoryCode"].ToString();
            }

            var Category = _context.Category.Where(m => m.CategoryCode == Catcode).FirstOrDefault();
            ViewData["CategoryName"] = Category.Name;

           // ViewData["CategoryCode"] = new SelectList(_context.Category, "CategoryCode", "CategoryCode");
            return View();
        }

        // POST: Measure/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MeasureCode,Name,CategoryCode,RatioToBase")] Measure measure)
        {
            string Catcode = string.Empty;
            if (Request.Cookies["CategoryCode"] != null)
            {
                Catcode = Request.Cookies["CategoryCode"].ToString();
            }
            //var Category = _context.Category.Where(m => m.CategoryCode == Catcode).FirstOrDefault();
            //ViewData["CategoryName"] = Category.Name;

            measure.CategoryCode = Catcode;

            if (ModelState.IsValid)
            {
                _context.Add(measure);
                await _context.SaveChangesAsync();
                if(measure.RatioToBase==1)
                {
                    var name = _context.Category.Where(x => x.CategoryCode == measure.CategoryCode).FirstOrDefault();
                    name.MeasureCode = measure.MeasureCode;
                    _context.Update(measure);
                    _context.SaveChanges();
                    //ViewData["MeasureName"] = measure.Name;
                }
                TempData["message"] = "Your  measure code has been added in the database successfully";
                return RedirectToAction(nameof(Index));
            }
            // ViewData["CategoryCode"] = new SelectList(_context.Category, "CategoryCode", "CategoryCode", measure.CategoryCode);
            
            return View(measure);
        }

        // GET: Measure/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var measure = await _context.Measure.FindAsync(id);
            if (measure == null)
            {
                return NotFound();
            }
            ViewData["CategoryCode"] = new SelectList(_context.Category, "CategoryCode", "CategoryCode", measure.CategoryCode);
            return View(measure);
        }

        // POST: Measure/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MeasureCode,Name,CategoryCode,RatioToBase")] Measure measure)
        {
            if (id != measure.MeasureCode)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(measure);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MeasureExists(measure.MeasureCode))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryCode"] = new SelectList(_context.Category, "CategoryCode", "CategoryCode", measure.CategoryCode);
            return View(measure);
        }

        // GET: Measure/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var measure = await _context.Measure
                .Include(m => m.CategoryCodeNavigation)
                .FirstOrDefaultAsync(m => m.MeasureCode == id);
            if (measure == null)
            {
                return NotFound();
            }

            return View(measure);
        }

        // POST: Measure/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var measure = await _context.Measure.FindAsync(id);
            _context.Measure.Remove(measure);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MeasureExists(string id)
        {
            return _context.Measure.Any(e => e.MeasureCode == id);
        }
    }
}

Cooking/Cooking/Views/Category/Create.cshtml
@model Cooking.Models.Category

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CategoryCode" class="control-label"></label>
                <input asp-for="CategoryCode" class="form-control" />
                <span asp-validation-for="CategoryCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeasureCode" class="control-label"></label>
                <input asp-for="MeasureCode" class="form-control"/>
                @*<select asp-for="MeasureCode" class="form-control" asp-items="ViewBag.MeasureCode"></select>*@
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cooking/Cooking/Views/Category/Delete.cshtml
@model Cooking.Models.Category

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeasureCodeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeasureCodeNavigation.MeasureCode)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CategoryCode" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Cooking/Cooking/Views/Category/Details.cshtml
@model Cooking.Models.Category

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeasureCodeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeasureCodeNavigation.MeasureCode)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CategoryCode">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Cooking/Cooking/Views/Category/Edit.cshtml
@model Cooking.Models.Category

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CategoryCode" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeasureCode" class="control-label"></label>
                <select asp-for="MeasureCode" class="form-control" asp-items="ViewBag.MeasureCode"></select>
                <span asp-validation-for="MeasureCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cooking/Cooking/Views/Category/Index.cshtml
@model IEnumerable<Cooking.Models.Category>

@{
    ViewData["Title"] = "Measurement Categories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CategoryCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.MeasureCodeNavigation)*@
                Base Measure
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                
                    @Html.DisplayFor(modelItem => item.CategoryCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeasureCodeNavigation.MeasureCode)
            </td>
            <td>
                <a asp-controller="Measure" asp-action="Index" asp-route-CategoryCode="@item.CategoryCode">Measures</a> |
                <a asp-action="Edit" asp-route-id="@item.CategoryCode">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CategoryCode">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CategoryCode">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>